version: '3.4'
services:
  be:
    container_name: pbl6_dotnet_parking
    image: pbl6_dotnet_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      target: development
    ports: 
      - 5000:5000
    volumes:
      - .:/src
  